const $=s=>document.querySelector(s),F=$('#calculator-form'),E=$('#error-box'),P=$('#result-panel'),B=$('#result-rows'),K='bo-calc-v1';
const D={startBalance:'0.01450058',goalMode:'withdrawJpy',targetJpy:'30000',targetEth:'2',ethJpy:'289327',payoutPercent:'90',reinvestPercent:'50',minStake:'0.005',maxStake:'0.5',stakeStep:'0.0005',roundingMode:'floor',withdrawalStep:'1',reserveEth:'1',maxRounds:'500'};
const yen=n=>new Intl.NumberFormat('ja-JP',{maximumFractionDigits:0}).format(Math.round(n));
const eth=(n,d=8)=>Number(n).toLocaleString('ja-JP',{maximumFractionDigits:d});
function cfg(){return Object.fromEntries(new FormData(F).entries())}
function set(v){Object.entries({...D,...v}).forEach(([k,x])=>{let f=F.elements.namedItem(k);if(f)f.value=x});sync()}
function sync(){let m=F.elements.goalMode.value;$('#target-jpy-field').hidden=m!=='withdrawJpy';$('#target-eth-field').hidden=m==='withdrawJpy';document.querySelectorAll('[data-withdrawal-field]').forEach(x=>x.hidden=m==='balanceEth');$('#target-eth-label').textContent=m==='balanceEth'?'目標残高':'目標出金量'}
function stepRound(v,s,m){let q=v/s;return (m==='ceil'?Math.ceil(q-1e-12):m==='round'?Math.round(q):Math.floor(q+1e-12))*s}
function calc(c){let bal=+c.startBalance,min=+c.minStake,max=+c.maxStake,step=+c.stakeStep,pay=+c.payoutPercent/100,re=+c.reinvestPercent/100,px=+c.ethJpy,res=+c.reserveEth,ws=+c.withdrawalStep;
if([bal,min,max,step,pay,re,px].some(x=>!Number.isFinite(x)||x<=0))throw Error('入力値を確認してください。');if(max<min)throw Error('最大掛け金は最小掛け金以上にしてください。');
let exact,out=0,target;if(c.goalMode==='withdrawJpy')exact=+c.targetJpy/px;else exact=+c.targetEth;if(!Number.isFinite(exact)||exact<=0)throw Error('目標値を確認してください。');if(c.goalMode==='balanceEth')target=exact;else{out=Math.ceil((exact-1e-12)/ws)*ws;target=out+res}
let rows=[{r:0,a:bal}],limit=Math.min(+c.maxRounds||500,5000);for(let r=1;bal+1e-12<target&&r<=limit;r++){if(bal<min-1e-12)break;let stake=stepRound(bal*re,step,c.roundingMode);stake=Math.max(min,Math.min(max,stake,bal));let before=bal,profit=stake*pay;bal+=profit;bal=+bal.toFixed(8);rows.push({r,b:before,s:stake,p:profit,a:bal})}
return{rows,w:rows.length-1,reached:bal+1e-10>=target,bal,target,out,exact,remain:bal-out,px}}
function render(r){$('#wins-value').textContent=r.reached?`${r.w}連勝`:'到達不可';$('#target-balance-value').textContent=`${eth(r.target)} ETH`;$('#final-balance-value').textContent=`${eth(r.bal)} ETH`;$('#final-jpy-value').textContent=`約${yen(r.bal*r.px)}円`;$('#withdrawal-card').hidden=!r.out;$('#withdrawal-value').textContent=`${eth(r.out)} ETH`;$('#withdrawal-jpy-value').textContent=`約${yen(r.out*r.px)}円`;$('#remaining-value').textContent=r.out?`${eth(r.remain)} ETH`:'—';$('#remaining-jpy-value').textContent=r.out?`約${yen(r.remain*r.px)}円`:'';$('#goal-detail').textContent=r.out?`目標に必要な${eth(r.exact)} ETHを出金単位に従って${eth(r.out)} ETHへ切り上げ、出金後に${eth(+F.elements.reserveEth.value)} ETHを残す計算です。`:`指定した目標残高${eth(r.target)} ETHへの到達回数です。`;
let f=document.createDocumentFragment();r.rows.forEach(x=>{let tr=document.createElement('tr');if(x.r===r.w&&r.reached)tr.className='target-row';let a=x.r? [x.r,eth(x.b)+' ETH',eth(x.s)+' ETH',eth(x.p)+' ETH',eth(x.a)+' ETH','約'+yen(x.a*r.px)+'円']:['開始','—','—','—',eth(x.a)+' ETH','約'+yen(x.a*r.px)+'円'];a.forEach(v=>{let td=document.createElement('td');td.textContent=v;tr.append(td)});f.append(tr)});B.replaceChildren(f);$('#row-count').textContent=`${r.w}回分`;window.last=r;P.hidden=false;if(!r.reached){E.hidden=false;E.textContent='設定した上限回数内に目標へ到達しませんでした。'}}
function run(scroll=false){E.hidden=true;try{let r=calc(cfg());render(r);localStorage.setItem(K,JSON.stringify(cfg()));if(scroll)P.scrollIntoView({behavior:'smooth'})}catch(e){P.hidden=true;E.hidden=false;E.textContent=e.message}}
async function price(){let b=$('#fetch-price');b.disabled=true;$('#price-status').textContent='価格を取得中…';try{let p;try{let j=await (await fetch('https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=jpy',{cache:'no-store'})).json();p=+j.ethereum.jpy}catch{let j=await (await fetch('https://api.coinbase.com/v2/prices/ETH-JPY/spot',{cache:'no-store'})).json();p=+j.data.amount}if(!p)throw 0;F.elements.ethJpy.value=Math.round(p);$('#price-status').textContent=`取得済み：1 ETH ≈ ${yen(p)}円`;run()}catch{$('#price-status').textContent='自動取得できませんでした。手動入力してください。'}b.disabled=false}
function csv(){let r=window.last;if(!r)return;let a=[['連勝数','勝負前残高(ETH)','掛け金(ETH)','勝利利益(ETH)','勝利後残高(ETH)','残高円換算']];r.rows.forEach(x=>a.push(x.r?[x.r,x.b,x.s,x.p,x.a,Math.round(x.a*r.px)]:['開始','','','',x.a,Math.round(x.a*r.px)]));let u=URL.createObjectURL(new Blob(['\ufeff'+a.map(x=>x.join(',')).join('\n')],{type:'text/csv'})),l=document.createElement('a');l.href=u;l.download='eth-simulation.csv';l.click();URL.revokeObjectURL(u)}
F.addEventListener('submit',e=>{e.preventDefault();run(true)});F.addEventListener('change',e=>{if(e.target.name==='goalMode')sync();run()});F.addEventListener('input',()=>localStorage.setItem(K,JSON.stringify(cfg())));$('#fetch-price').onclick=price;$('#export-csv').onclick=csv;$('#reset-form').onclick=()=>{localStorage.removeItem(K);set(D);run()};$('#theme-toggle').onclick=()=>{let d=document.documentElement,t=d.dataset.theme==='dark'?'light':'dark';d.dataset.theme=t;localStorage.setItem('bo-theme',t)};document.documentElement.dataset.theme=localStorage.getItem('bo-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');try{set(JSON.parse(localStorage.getItem(K)||'{}'))}catch{set(D)}run();price();